export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const GET_USER_LOADING = 'GET_USER_LOADING';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAILURE = 'GET_USER_FAILURE';

export const GET_ORGS_LOADING = 'GET_ORGS_LOADING';
export const GET_ORGS_SUCCESS = 'GET_ORGS_SUCCESS';
export const GET_ORGS_FAILURE = 'GET_ORGS_FAILURE';

export const GET_ORG_LOADING = 'GET_ORG_LOADING';
export const GET_ORG_SUCCESS = 'GET_ORG_SUCCESS';
export const GET_ORG_FAILURE = 'GET_ORG_FAILURE';

export const CREATE_ORG_LOADING = 'CREATE_ORG_LOADING';
export const CREATE_ORG_SUCCESS = 'CREATE_ORG_SUCCESS';
export const CREATE_ORG_FAILURE = 'CREATE_ORG_FAILURE';
export const CREATE_ORG_RESET = 'CREATE_ORG_RESET';

export const EDIT_ORG_LOADING = 'EDIT_ORG_LOADING';
export const EDIT_ORG_SUCCESS = 'EDIT_ORG_SUCCESS';
export const EDIT_ORG_FAILURE = 'EDIT_ORG_FAILURE';
export const EDIT_ORG_RESET = 'EDIT_ORG_RESET';

export const DELETE_ORG_LOADING = 'DELETE_ORG_LOADING';
export const DELETE_ORG_SUCCESS = 'DELETE_ORG_SUCCESS';
export const DELETE_ORG_FAILURE = 'DELETE_ORG_FAILURE';
export const DELETE_ORG_RESET = 'DELETE_ORG_RESET';
