version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: cd backend && yarn install --frozen-lockile
      - run: cd frontend && yarn install --frozen-lockile && yarn build
      - persist_to_workspace:
          root: ./
          # must include anything needed to build/tag/push docker image
          paths:
            - src
            - node_modules
            - package.json
            - yarn.lock
            - .mvpstudio
            - .git
            - Dockerfile

  publish:
    docker:
      - image: circleci/python:3
    steps:
      - attach_workspace:
          at: ./
      - setup_remote_docker:
          docker_layer_caching: true
      - run: curl https://raw.githubusercontent.com/MVPStudio/build_setup/master/build_tag_push.sh | bash

workflows:
  version: 2
  build-publish-deploy:
    jobs:
      - build
      - publish:
          context: dockerhub-publish
          requires:
            - build
          filters:
            branches:
              only: master
