export const categories = [
    'Agriculture',
    'Animals',
    'Business',
    'Cultural',
    'Education',
    'Emergency',
    'Environmental',
    'Health',
    'Housing',
    'LGBTQ',
    'Other',
    'Political',
    'Recreation',
    'Social',
    'Spiritual',
    'Technology',
    'Transportation',
    'Youth',
]

export const tags = [
    { label: 'Food Box Pantry' },
    { label: 'Clothing' },
    { label: 'Family Shelter' },
    { label: 'The Dining Room' },
    { label: 'Fourth Sunday Breakfast' },
    { label: 'FISH' },
    { label: 'SquareOne' },
    { label: 'Habitat for Humanity' },
    { label: 'First Place' },
    { label: 'Catholic Community Services' },
    { label: 'SVDP' },
    { label: 'Egan Warming Centers' },
    { label: 'Home Starter Kits' },
    { label: 'Conestoga Huts' },
    { label: 'Laundry Love' },
    { label: 'Clothing Barrel' },
    { label: 'FFLC' },
    { label: 'ShelterCare' },
    { label: 'H2O Bags' },
    { label: 'Bikes & Burritos' },
    { label: 'Good Samaritan Ministry' },
    { label: 'Helping Hand Room' },
    { label: 'Occupy Medical' },
    { label: 'Opportunity Village' },
    { label: 'Eugene Mission' },
    { label: 'Lunch Bags' },
    { label: 'Hosea Youth Services' },
    { label: 'Community Garden' },
    { label: 'First Saturday Breakfast' },
    { label: 'Riverstone Clinic' },
    { label: 'Food Rescue' },
    { label: 'Generosity Feeds' },
    { label: 'Homeless Packets' },
    { label: 'Center for Community Counseling' },
];

export const states = [ 
    'AL', 
    'AK', 
    'AS', 
    'AZ', 
    'AR', 
    'CA', 
    'CO', 
    'CT', 
    'DE', 
    'DC', 
    'FM', 
    'FL', 
    'GA', 
    'GU', 
    'HI', 
    'ID', 
    'IL', 
    'IN', 
    'IA', 
    'KS', 
    'KY', 
    'LA', 
    'ME', 
    'MH', 
    'MD', 
    'MA', 
    'MI', 
    'MN', 
    'MS', 
    'MO', 
    'MT', 
    'NE', 
    'NV', 
    'NH', 
    'NJ', 
    'NM', 
    'NY', 
    'NC', 
    'ND', 
    'MP', 
    'OH', 
    'OK', 
    'OR', 
    'PW', 
    'PA', 
    'PR', 
    'RI', 
    'SC', 
    'SD', 
    'TN', 
    'TX', 
    'UT', 
    'VT', 
    'VI', 
    'VA', 
    'WA', 
    'WV', 
    'WI', 
    'WY' 
];
