apiVersion: v1
kind: Service
metadata:
  name: ecan-soar-mongodb
  namespace: prod-ecan-soar
  labels:
    app: ecan-soar-mongodb
spec:
  ports:
    - port: 27017
      name: mongodb
  selector:
    app: ecan-soar-mongodb
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prod-ecan-soar-mongodb-deploy
  namespace: prod-ecan-soar
spec:
  serviceName: ecan-soar-mongodb
  selector:
    matchLabels:
      app: ecan-soar-mongodb
  replicas: 1
  template:
    metadata:
      labels:
        app: ecan-soar-mongodb
    spec:
      containers:
        - name: mongo
          image: mongo:3.6
          resources:
            limits:
              cpu: 1
              memory: 1000Mi
            requests:
              cpu: 0.5
              memory: 500Mi
          env:
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ecan-soar-mongo-credentials
                  key: password
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: ecan-soar-mongo-credentials
                  key: username
          ports:
            - containerPort: 27017
              name: mongo
          volumeMounts:
            - name: mongodata
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: mongodata
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 30Gi
